# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Credibility Coalition
email: hello@credibilitycoalition.org
description: >- # this means to ignore newlines until "baseurl:"
  We are an interdisciplinary community committed to improving our information ecosystems
  and media literacy through transparent and collaborative exploration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - pages:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'page'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - jobPostings:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'jobPosting'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - profiles:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'profile'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - navigations:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'navigation'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - updates:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'update'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - mentions:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'mention'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - organisations:
        space: ENV_CONTENTFUL_CC_SPACE_ID
        access_token: ENV_CONTENTFUL_CC_ACCESS_TOKEN
        cda_query:
          content_type: 'organisation'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'

# Generate pages from Contentful and CredMap data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.pages.page'
    template: 'page'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.jobPostings.jobPosting'
    template: 'job'
    name: 'slug'
    dir: 'jobs'
  - data: 'credcatalog.initiatives'
    template: 'project'
    name: 'Name'
    dir: 'credcatalog/project'
  - data: 'credcatalog.funders'
    template: 'funder'
    name: 'Name'
    dir: 'credcatalog/funder'
